INSERT INTO TODO (MEMBER_SEQ, CONTENT) VALUES (0, '공부하기');
INSERT INTO TODO (MEMBER_SEQ, CONTENT) VALUES (0, '운동하기');

INSERT INTO MEMBER (EMAIL, PASSWORD, NICKNAME) VALUES ('steadyman999@gmail.com', 'password', 'steadyman');